language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6
  - "nightly"
  - "pypy3"
matrix:
  allow_failures:
    - python: "nightly"
    - python: "pypy3"
branches:
  only:
    - master
    - develop
install:
  - "pip install pytest"
  - "pip install pytest-cov"
  - "pip install python-coveralls"
  - "pip install -r requirements.txt -e ."
script: py.test tests --cov flask_pybankid --cov-report term-missing
after_success:
  - coveralls
