language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
branches:
  only:
    - master
    - develop
install:
  - "pip install pytest"
  - "pip install -r requirements.txt -e ."
script: py.test tests
